global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "locsnap-spring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["locsnap-backend:8080"]
        labels:
          application: "locsnap"
